

// // Reverse a String With a Decrementing For Loop
// function reverseString(stringToConvert) {
//     let reversedString = "";
//     for (let i = stringToConvert.length; i >= 0; i--) {
//         // console.log(stringToConvert.length);
//         // console.log(i);        
//         // reversedString += stringToConvert[i]; // or reversedString = reversedString + stringToConvert[i];
//         reversedString = `${reversedString} \n ${stringToConvert[i]}`;
//     }
//     console.log([...stringToConvert])
//     console.log(stringToConvert);
//     console.log(reversedString);
//     return stringToConvert;
// }
// reverseString("PRASAD")




// // 3 With Spread Operator
// let string = "Prasad Sawant"
// const answer = [...string]
// console.log(answer)

// const reverseString = [...string].reverse()
// console.log(reverseString)

// const joining = [string].join()
// console.log(joining)



// // 2
// let string
// function reverseString(string) {
//     const reverseString = string.split("").reverse().join("")
//     console.log(reverseString)
// }



// // 1
// let string = "Prasad Sawant"
// const reverseString = string.split("").reverse().join("");
// console.log(reverseString)
